# Site settings
title: Leon Liang's Resume
description: leonliang10's CV
favicon: /assets/img/avatar.JPG
baseurl: https://leonliang10.github.io/
url: https://leonliang10.github.io
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Leon Liang
  title: Aspiring Data Scientist
  address: Bay Area, California
  email: leonliang10 [at] berkeley [dot] com
  link: 
  weibo:
  github: leonliang10
  linkedin: leonliang10
  twitter: 
  gavatar: /resumecard/assets/img/me.JPG
  stackoverflow:

  workHistory:
    - work1:
      company: Lockheed Martin Space Systems Company
      location: Sunnyvale, California, United States
      title: Data Scientist Intern
      started: 2016
      duration: (May 2016 - Present)
      description: Data Scientist Intern that supported Market Analysis Team within Competitive Intelligence to analyze space industry. Developed a sentiment analysis tool (Java) using NLP to generate LM’s major competitors’ trending using over 3,000 articles scrapped from space industry related news websites. Developed a predictive analytics tool (R) that predicts space project costs using regression trees with existing LM database consisting of over 15,000 data of previous space projects. Generated statistical reports of estimated project costs from predictive analytics tool results for the team to use on market analysis and strategic planning for future space projects.
    - work2:
      company: UC Berkeley Vision Computing Lab
      location: Berkeley, California, United States
      started: 2016
      duration: (Mar 2016 - Present)
      description: Research Assistant for Computer vision research that focuses on the analysis and finding of what photo parameters will generate a more realistic photo of the real world. The goal is the utilize machine learning to learn the parameters. I'm also revamping the iOS photo editing application to collect more useful photo data
    - work3:
      company: UC Berkeley EECS Accounting
      location: Berkeley, California, United States
      started: 2015
      duration: (Oct 2015 - Present)
      description: Accounting assistant assisting EECS Accounting group with financial projects and processing EECS professosr and department fundings. Supporting accounting group with departmental funding from thousands to millions of dollars. Updated the EECS textbook database for faster and simpler data entry for future users
    - work4:
      company: UC Berkeley Physics
      location: Berkeley, California, United States
      started: 2014
      duration: (Aug 2014 - May 2016)
      description: Online Database of Extragalactic Transient Theoretical Astrophysics (ODETTA) is an open source astrophysics website and database that uses supernovae data gathered from the Lawrence Berkeley National Laboratory to run computer simulations on the NERSC supercomputers to improve our knowledge in supernovae. This research aims to apply machine learning techniques to help analyze and predict the categories of supernova data and its features. Applied Principal Component Analysis (PCA) to extract key features from over 1,000,000 supernova data with Python using NumPy, SciPy, and MatPlotLib to build predictive models. Applied machine learning to generate K-means Clustering models to predict the supernova categories of future observed supernova datasets. Handled the data processing pipeline for all observed and computer simulated supernova data
  educationHistory:
    - education1:
      organization: University of California, Berkeley College of Engineering
      location: Berkeley, California, United States
      degree: Bachelor of Science
      major: Engineering Mathematics and Statistics with emphasis in Computer Science
      started: 2013
      duration: (2013 - 2017)
      description: My current major is engineering mathematics and statistics with emphasis in computer science. Relevant coursework for my major includes many of both theoretical and applied mathematics, statistics, and computer science courses. gRelevant courseworks Machine Learning, Artificial Intelligence, Efficient Algorithms and Intractable Problems, Data Structures, Concepts in Probability, Concepts in Data Computing, Linear Algebra, Numerical Analysis, Real Analysis, Complex Analysis
  languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: Cantonese
      proficiency: Native
    - language3:
      name: Mandarin
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: Python
      percentage: 100%
    - skill2:
      name: R
      percentage: 100%
    - skill3:
      name: Java
      percentage: 90%
    - skill4:
      name: MATLAB
      percentage: 85%
    - skill5:
      name: Swift
      percentage: 50%
    - skill6:
      name: C
      percentage: 30%
